baseURL = 'https://rishika2024.github.io'
languageCode = 'en-us'
title = "Rishika Bera's Portfolio"
theme = 'pehtheme-hugo'
disqusShortname = ''

# Allow raw HTML in Markdown (needed for inline grids/HTML blocks)
ignoreLogs = ["warning-goldmark-raw-html"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true



[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Github'
url = 'https://github.com/rishika2024'
weight = 20

[[menus.main]]
name = 'Linkedn'
url = 'https://www.linkedin.com/in/rishika-bera-05b7b025a/'
weight = 30

[[menus.main]]
name = 'Email'
url = 'mailto:berarishika@gmail.com'
weight = 40

[module]
  [module.hugoVersion]
    extended = true
    min = "0.116.0"
    
[caches]
  [caches.images]
    dir = ':cacheDir/images'

